name: hydrosync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  health: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  google_fonts: ^6.2.1
  intl: ^0.18.0

  flutter_local_notifications: ^12.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
