// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2h6BHXz4Kjar5fVrlNWeWqkFOjiUYZtc',
    appId: '1:982965471607:web:4aca954ddaf28d1f233972',
    messagingSenderId: '982965471607',
    projectId: 'hydrosync-2eb5d',
    authDomain: 'hydrosync-2eb5d.firebaseapp.com',
    storageBucket: 'hydrosync-2eb5d.appspot.com',
    measurementId: 'G-G0WK9THVT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1Tmzow87jL1rsQQov7nZIWHIo0fVQgs',
    appId: '1:982965471607:android:232824767d9c2105233972',
    messagingSenderId: '982965471607',
    projectId: 'hydrosync-2eb5d',
    storageBucket: 'hydrosync-2eb5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW-jB61QM4dmk3KmO40dX-umOj612P9rA',
    appId: '1:982965471607:ios:ce525730e7568185233972',
    messagingSenderId: '982965471607',
    projectId: 'hydrosync-2eb5d',
    storageBucket: 'hydrosync-2eb5d.appspot.com',
    iosBundleId: 'com.example.hydrosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW-jB61QM4dmk3KmO40dX-umOj612P9rA',
    appId: '1:982965471607:ios:ce525730e7568185233972',
    messagingSenderId: '982965471607',
    projectId: 'hydrosync-2eb5d',
    storageBucket: 'hydrosync-2eb5d.appspot.com',
    iosBundleId: 'com.example.hydrosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2h6BHXz4Kjar5fVrlNWeWqkFOjiUYZtc',
    appId: '1:982965471607:web:1d217d16b47e394b233972',
    messagingSenderId: '982965471607',
    projectId: 'hydrosync-2eb5d',
    authDomain: 'hydrosync-2eb5d.firebaseapp.com',
    storageBucket: 'hydrosync-2eb5d.appspot.com',
    measurementId: 'G-NTNKPGM2W9',
  );
}
